name: idpay_payment_package
description: A package for making easy, payment with idpay
version: 0.0.1
homepage: https://github.com/alirezat66/idpay_payment_package.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.2
dev_dependencies:
  flutter_test:
    sdk: flutter
